#! /usr/bin/python
import math

pmarbs = []
pows = 49 
pmarbs.append("W")
for i in range(pows):
    count = 0
    j = 0
    ran = int(pow(2, i))   
    marker = len(pmarbs) - 1 
    while (j < ran):        
        #potential marble choice
        pot = pmarbs[marker - j]
        pot1 = pot + "W"
        pot2 = pot + "B"

        if ((len(pot2) > (i+1)) and pot2.count('W') < pot2.count('B')):
            count += 1
        else:
            pmarbs.append(pot2)
        pmarbs.append(pot1)

#        if(len(pmarbs[0]) < i):
#           pmarbs.pop(0)
#           marker -= 1
        j += 1
       

    if (count != 0):
        print(count)
        print("length of pmarbs = %s" % len(pmarbs))
