#! /usr/bin/python
def odaev(n):
    
    print n
    if (n % 2 == 0):
        return (odaev(int(n/2)))
    elif(n % 2 == 1 and n != 1):
        return (odaev(3*n + 1))
    else:
        return 1;

inp = int(input("input a number: "))
while (inp != 0):
    odaev(inp)
    inp = int(input("input a number (input 0 to quit): "))
