#! /usr/bin/perl
my @array1 = (0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ,13, 14, 15, 16, 17, 18,
               19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34);
my @array2 = ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
              'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
$i = 0;
while ($i < scalar @array1)
{
    
    print "$array1[$i]\n";
    print $array2[$i];
    $i++;
}


print "Hi\n";
$returned = &tester(@array1);
print "$returned\n";
print("$i, $j\n");

sub tester
{
    my($i, $j);
    $i = 5;
    $j = 6;
    print"$_[0]\n";
    print"$_[1]\n";
    print"$_[2]\n";
    return $_[((scalar @array1) - 1)];
}


open(INF, "<", "inputFile.txt") or die "unable to open input file";

{
    local $/;
    $in_buffer = <INF>;
}
print "$in_buffer";

print "test\n";

$x = 1;

{
    local $x;
    $x = 2;
    print "inside block: $x \n";
}

print $x."\n";

$fruit = 'pears';

@fruits = ('apples', 'oranges');

foreach $fruit (@fruits)
{
    print "$fruit \n";
}

print "should be pears: $fruit \n";

$x = 17;

package A;
$x = 12;

package B;
$x = 20;

print "$B::x \n"; 



$lo = 'global';
$m = 'global';
A();
sub A 
{
local $lo = 'AAA';
my    $m  = 'AAA';
B();
}


sub B
{
print "B ",($lo eq 'AAA' ? 'can' : 'cannot')," see the value of lo set by A.\n";
print "B ",($m eq 'AAA' ? 'can' : 'cannot'), " see the value of m set by A.\n";
}
for (1 .. 50)
{
    my $x;
    $x++;
    print "\$x = $x\n";

}
