#! /usr/bin/perl

$string1 = "abcis a message";

if($string1 =~ m/abch??is/)
{
    print "matched: >$&<\n";
    print "after:  >$'<\n";
}

$string = "d.halden\@gmail.com";
if($string =~ m/(\w(\+|\.|))+@[a-zA-Z_]+?\.[a-zA-Z]{2,6}/)
{
    print "matched: >$&<\n";
}

